from sqlalchemy import Column, String, Integer, Float, DateTime, ForeignKey, Enum, JSON, Boolean, Text, Index
from sqlalchemy.dialects.postgresql import UUID
import uuid
import enum
from datetime import datetime, timezone
from app.core.database import Base

def utcnow():
    return datetime.now(timezone.utc)

class LedgerEntryType(str, enum.Enum):
    BOOKING = "BOOKING"
    SETTLEMENT = "SETTLEMENT"
    CANCELLATION = "CANCELLATION"
    REFUND = "REFUND"
    ADJUSTMENT = "ADJUSTMENT"

class PaymentMode(str, enum.Enum):
    CASH = "Cash"
    UPI = "UPI"
    CARD = "Card"
    OTHER = "Other"

class FinancialLedgerEntry(Base):
    """Immutable accounting entry for the temple ledger."""
    __tablename__ = "financial_ledger"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    temple_id = Column(UUID(as_uuid=True), ForeignKey("temples.id"), nullable=False, index=True)
    entry_type = Column(Enum(LedgerEntryType), nullable=False)
    ref_id = Column(String, nullable=False, index=True) # Reference to Booking/Refund/etc.
    amount = Column(Float, nullable=False)
    payment_mode = Column(String, nullable=False) # Store as string for flexibility
    
    # Revenue Split
    temple_revenue = Column(Float, default=0.0)
    priest_dakshina = Column(Float, default=0.0)
    donation_portion = Column(Float, default=0.0)
    
    # Metadata
    recorded_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    description = Column(Text, nullable=True)
    is_reconciled = Column(Boolean, default=False)
    settlement_id = Column(UUID(as_uuid=True), ForeignKey("daily_settlements.id"), nullable=True)
    
    # Hybrid/Offline Support
    sync_status = Column(String, default="PENDING") # PENDING, SYNCED, CONFLICT
    device_id = Column(String, nullable=True)
    offline_event_id = Column(String, nullable=True) # ID generated by the device
    
    created_at = Column(DateTime(timezone=True), default=utcnow)
    
    __table_args__ = (
        Index("idx_ledger_temple_ref", "temple_id", "ref_id"),
        Index("idx_ledger_sync", "sync_status"),
    )

class DailySettlement(Base):
    """Immutable daily closing snapshot."""
    __tablename__ = "daily_settlements"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    temple_id = Column(UUID(as_uuid=True), ForeignKey("temples.id"), nullable=False, index=True)
    settlement_date = Column(DateTime(timezone=True), nullable=False)
    
    # Aggregates
    opening_balance = Column(Float, default=0.0)
    total_cash = Column(Float, default=0.0)
    total_upi = Column(Float, default=0.0)
    total_card = Column(Float, default=0.0)
    total_dakshina = Column(Float, default=0.0)
    total_donations = Column(Float, default=0.0)
    
    # Reconciliation
    expected_total = Column(Float, nullable=False)
    actual_total = Column(Float, nullable=False)
    variance = Column(Float, default=0.0)
    variance_reason = Column(Text, nullable=True)
    
    # Governance
    status = Column(String, default="OPEN") # OPEN, CLOSED, AUDITED
    closed_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    approved_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    closed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Snapshots
    revenue_breakdown = Column(JSON, nullable=True) # Category-wise breakdown
    
    created_at = Column(DateTime(timezone=True), default=utcnow)
    updated_at = Column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)

class CashSession(Base):
    """Represents an operator's active shift/session."""
    __tablename__ = "cash_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    temple_id = Column(UUID(as_uuid=True), ForeignKey("temples.id"), nullable=False, index=True)
    operator_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    
    start_time = Column(DateTime(timezone=True), default=utcnow)
    end_time = Column(DateTime(timezone=True), nullable=True)
    
    opening_cash = Column(Float, default=0.0)
    closing_cash = Column(Float, nullable=True)
    total_collected = Column(Float, default=0.0)
    
    status = Column(String, default="ACTIVE") # ACTIVE, COMPLETED
    
    created_at = Column(DateTime(timezone=True), default=utcnow)

class BookingAdjustment(Base):
    """Audit trail for changes made to financial records."""
    __tablename__ = "booking_adjustments"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    temple_id = Column(UUID(as_uuid=True), ForeignKey("temples.id"), nullable=False, index=True)
    ledger_entry_id = Column(UUID(as_uuid=True), ForeignKey("financial_ledger.id"), nullable=False)
    
    old_amount = Column(Float, nullable=False)
    new_amount = Column(Float, nullable=False)
    reason = Column(String, nullable=False)
    adjusted_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    
    created_at = Column(DateTime(timezone=True), default=utcnow)
