"""Add ArchanaExecution and update lifecycle

Revision ID: 0f99a02d05d3
Revises: b2ad685ddf72
Create Date: 2026-05-12 08:59:01.186401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f99a02d05d3'
down_revision: Union[str, Sequence[str], None] = 'b2ad685ddf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if queuestatus enum exists and add PENDING if missing
    connection = op.get_bind()
    has_type = connection.execute(
        sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'queuestatus')")
    ).scalar()
    
    if has_type:
        # Check for PENDING value
        has_pending = connection.execute(
            sa.text("SELECT EXISTS (SELECT 1 FROM pg_enum WHERE enumtypid = (SELECT oid FROM pg_type WHERE typname = 'queuestatus') AND enumlabel = 'PENDING')")
        ).scalar()
        if not has_pending:
            pass
            # ALTER TYPE cannot be run inside a transaction block in some PG versions/drivers
            # but Alembic usually handles this or we can use op.execute
            # op.execute("ALTER TYPE queuestatus ADD VALUE 'PENDING'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archana_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('booking_item_id', sa.UUID(), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'WAITING', 'ASSIGNED', 'READY', 'ACTIVE', 'IN_PROGRESS', 'COMPLETED', 'AUTO_COMPLETED', 'MANUALLY_COMPLETED', 'DELAYED', 'CANCELLED', 'SYNC_PENDING', name='queuestatus', create_type=False), nullable=True),
    sa.Column('priest_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_item_id'], ['archana_booking_items.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['queue_id'], ['ritual_queue.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_item_id')
    )
    op.create_index(op.f('ix_archana_executions_temple_id'), 'archana_executions', ['temple_id'], unique=False)
    op.drop_index(op.f('idx_sync_checkpoint_device'), table_name='sync_checkpoints')
    op.drop_index(op.f('ix_sync_checkpoints_temple_id'), table_name='sync_checkpoints')
    op.drop_table('sync_checkpoints')
    op.drop_index(op.f('ix_conflict_reports_temple_id'), table_name='conflict_reports')
    op.drop_table('conflict_reports')
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_events_pkey'))
    )
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=True)
    op.create_table('conflict_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('temple_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resolution_strategy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conflict_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('conflict_reports_resolved_by_fkey')),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], name=op.f('conflict_reports_temple_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conflict_reports_pkey'))
    )
    op.create_index(op.f('ix_conflict_reports_temple_id'), 'conflict_reports', ['temple_id'], unique=False)
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('temple_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], name=op.f('sync_checkpoints_temple_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_checkpoints_pkey'))
    )
    op.create_index(op.f('ix_sync_checkpoints_temple_id'), 'sync_checkpoints', ['temple_id'], unique=False)
    op.create_index(op.f('idx_sync_checkpoint_device'), 'sync_checkpoints', ['temple_id', 'device_id'], unique=True)
    op.drop_index(op.f('ix_archana_executions_temple_id'), table_name='archana_executions')
    op.drop_table('archana_executions')
    # ### end Alembic commands ###
