"""add_hall_booking_refund_governance

Revision ID: 25b7b6524acd
Revises: hardening_pass_005_seed_additional_permissions
Create Date: 2026-05-31 13:58:48.046840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25b7b6524acd'
down_revision: Union[str, Sequence[str], None] = 'hardening_pass_005_seed_additional_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refund_method', sa.String(), nullable=False),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refund_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount_paid_before', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_paid_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status_before', sa.String(), nullable=True),
    sa.Column('payment_status_after', sa.String(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('rejected_by', sa.UUID(), nullable=True),
    sa.Column('approval_request_id', sa.UUID(), nullable=True),
    sa.Column('review_remarks', sa.Text(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['hall_bookings.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refund_history_approval_req', 'refund_history', ['approval_request_id'], unique=False)
    op.create_index('idx_refund_history_booking_id', 'refund_history', ['booking_id'], unique=False)
    op.create_index('idx_refund_history_processed_at', 'refund_history', ['processed_at'], unique=False)
    op.create_index('idx_refund_history_requested_at', 'refund_history', ['requested_at'], unique=False)
    op.create_index('idx_refund_history_tenant_proc_at', 'refund_history', ['temple_id', 'processed_at'], unique=False)
    op.create_index('idx_refund_history_tenant_req_at', 'refund_history', ['temple_id', 'requested_at'], unique=False)
    op.create_index('idx_refund_history_tenant_status', 'refund_history', ['temple_id', 'status'], unique=False)
    op.create_index('idx_refund_history_tenant_type', 'refund_history', ['temple_id', 'refund_type'], unique=False)
    op.create_index(op.f('ix_refund_history_booking_id'), 'refund_history', ['booking_id'], unique=False)
    op.create_index(op.f('ix_refund_history_status'), 'refund_history', ['status'], unique=False)
    op.create_index(op.f('ix_refund_history_temple_id'), 'refund_history', ['temple_id'], unique=False)
    op.add_column('hall_bookings', sa.Column('refund_status', sa.String(), nullable=False, server_default='NONE'))
    op.add_column('hall_bookings', sa.Column('has_pending_refund', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('hall_bookings', sa.Column('last_refund_history_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_hall_bookings_has_pending_refund'), 'hall_bookings', ['has_pending_refund'], unique=False)
    op.create_foreign_key(None, 'inventory_invoices', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'inventory_invoices', 'users', ['deleted_by'], ['id'])
    op.drop_constraint(op.f('fk_inventory_item_requests_issued_by_user_id_users'), 'inventory_item_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_item_requests_requested_by_user_id_users'), 'inventory_item_requests', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventory_item_requests_approved_by_user_id_users'), 'inventory_item_requests', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_item_requests', 'users', ['approved_by_user_id'], ['id'])
    op.create_foreign_key(None, 'inventory_item_requests', 'users', ['issued_by_user_id'], ['id'])
    op.create_foreign_key(None, 'inventory_item_requests', 'users', ['requested_by_user_id'], ['id'])
    op.create_index(op.f('ix_inventory_payment_transactions_invoice_id'), 'inventory_payment_transactions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_inventory_payment_transactions_payment_date'), 'inventory_payment_transactions', ['payment_date'], unique=False)
    op.create_index(op.f('ix_inventory_payment_transactions_temple_id'), 'inventory_payment_transactions', ['temple_id'], unique=False)
    op.alter_column('users', 'media_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'audit_trail',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'audit_trail',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'media_urls',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_payment_transactions_temple_id'), table_name='inventory_payment_transactions')
    op.drop_index(op.f('ix_inventory_payment_transactions_payment_date'), table_name='inventory_payment_transactions')
    op.drop_index(op.f('ix_inventory_payment_transactions_invoice_id'), table_name='inventory_payment_transactions')
    op.drop_constraint(None, 'inventory_item_requests', type_='foreignkey')
    op.drop_constraint(None, 'inventory_item_requests', type_='foreignkey')
    op.drop_constraint(None, 'inventory_item_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fk_inventory_item_requests_approved_by_user_id_users'), 'inventory_item_requests', 'users', ['approved_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_inventory_item_requests_requested_by_user_id_users'), 'inventory_item_requests', 'users', ['requested_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_inventory_item_requests_issued_by_user_id_users'), 'inventory_item_requests', 'users', ['issued_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'inventory_invoices', type_='foreignkey')
    op.drop_constraint(None, 'inventory_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_hall_bookings_has_pending_refund'), table_name='hall_bookings')
    op.drop_column('hall_bookings', 'last_refund_history_id')
    op.drop_column('hall_bookings', 'has_pending_refund')
    op.drop_column('hall_bookings', 'refund_status')
    op.drop_index(op.f('ix_refund_history_temple_id'), table_name='refund_history')
    op.drop_index(op.f('ix_refund_history_status'), table_name='refund_history')
    op.drop_index(op.f('ix_refund_history_booking_id'), table_name='refund_history')
    op.drop_index('idx_refund_history_tenant_type', table_name='refund_history')
    op.drop_index('idx_refund_history_tenant_status', table_name='refund_history')
    op.drop_index('idx_refund_history_tenant_req_at', table_name='refund_history')
    op.drop_index('idx_refund_history_tenant_proc_at', table_name='refund_history')
    op.drop_index('idx_refund_history_requested_at', table_name='refund_history')
    op.drop_index('idx_refund_history_processed_at', table_name='refund_history')
    op.drop_index('idx_refund_history_booking_id', table_name='refund_history')
    op.drop_index('idx_refund_history_approval_req', table_name='refund_history')
    op.drop_table('refund_history')
    # ### end Alembic commands ###
