"""add_devotee_profile_extended_fields

Revision ID: 27e063926090
Revises: 2e6ba722c3dd
Create Date: 2026-06-22 20:34:24.013216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e063926090'
down_revision: Union[str, Sequence[str], None] = '2e6ba722c3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'archana_executions', 'users', ['acknowledged_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('devotee_profiles', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('devotee_profiles', sa.Column('hindu_month', sa.String(), nullable=True))
    op.add_column('devotee_profiles', sa.Column('hindu_star', sa.String(), nullable=True))
    op.add_column('devotee_profiles', sa.Column('family_members', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('devotee_profiles', sa.Column('favorite_gods', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('devotee_profiles', sa.Column('favorite_temples', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.create_index(op.f('ix_temple_key_personnels_temple_id'), 'temple_key_personnels', ['temple_id'], unique=False)
    op.drop_constraint(op.f('temple_key_personnels_created_by_fkey'), 'temple_key_personnels', type_='foreignkey')
    op.drop_constraint(op.f('temple_key_personnels_updated_by_fkey'), 'temple_key_personnels', type_='foreignkey')
    op.create_foreign_key(None, 'temple_key_personnels', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'temple_key_personnels', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'temple_profiles', 'users', ['published_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temple_profiles', type_='foreignkey')
    op.drop_constraint(None, 'temple_key_personnels', type_='foreignkey')
    op.drop_constraint(None, 'temple_key_personnels', type_='foreignkey')
    op.create_foreign_key(op.f('temple_key_personnels_updated_by_fkey'), 'temple_key_personnels', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('temple_key_personnels_created_by_fkey'), 'temple_key_personnels', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_temple_key_personnels_temple_id'), table_name='temple_key_personnels')
    op.drop_column('devotee_profiles', 'favorite_temples')
    op.drop_column('devotee_profiles', 'favorite_gods')
    op.drop_column('devotee_profiles', 'family_members')
    op.drop_column('devotee_profiles', 'hindu_star')
    op.drop_column('devotee_profiles', 'hindu_month')
    op.drop_column('devotee_profiles', 'date_of_birth')
    op.drop_constraint(None, 'archana_executions', type_='foreignkey')
    # ### end Alembic commands ###
