"""add_settings_feature_visibility

Revision ID: 2f307da424dd
Revises: d5460663d845
Create Date: 2026-06-08 12:42:19.099718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f307da424dd'
down_revision: Union[str, Sequence[str], None] = 'd5460663d845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temple_website_settings', sa.Column('feature_visibility', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temple_website_settings', 'feature_visibility')
    # ### end Alembic commands ###
