"""Add Enterprise Hall Booking Models

Revision ID: 317851668047
Revises: 4ad52bc2761a
Create Date: 2026-05-17 17:54:43.964591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '317851668047'
down_revision: Union[str, Sequence[str], None] = '4ad52bc2761a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=False),
    sa.Column('held_by_user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['held_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking_hold_valid', 'booking_holds', ['hall_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_booking_holds_expires_at'), 'booking_holds', ['expires_at'], unique=False)
    op.create_index(op.f('ix_booking_holds_hall_id'), 'booking_holds', ['hall_id'], unique=False)
    op.create_index(op.f('ix_booking_holds_temple_id'), 'booking_holds', ['temple_id'], unique=False)
    op.create_table('booking_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=True),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('policy_value', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_policies_temple_id'), 'booking_policies', ['temple_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('adjustment_type', sa.String(), nullable=False),
    sa.Column('adjustment_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_temple_id'), 'pricing_rules', ['temple_id'], unique=False)
    op.create_table('venue_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_slots_temple_id'), 'venue_slots', ['temple_id'], unique=False)
    op.create_table('booking_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('previous_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['hall_bookings.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_audit_logs_booking_id'), 'booking_audit_logs', ['booking_id'], unique=False)
    op.create_index(op.f('ix_booking_audit_logs_temple_id'), 'booking_audit_logs', ['temple_id'], unique=False)
    op.create_table('booking_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('hall_id', sa.UUID(), nullable=False),
    sa.Column('primary_booking_id', sa.UUID(), nullable=False),
    sa.Column('overlapping_booking_id', sa.UUID(), nullable=True),
    sa.Column('conflict_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['overlapping_booking_id'], ['hall_bookings.id'], ),
    sa.ForeignKeyConstraint(['primary_booking_id'], ['hall_bookings.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_conflicts_temple_id'), 'booking_conflicts', ['temple_id'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['hall_bookings.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_table('payment_ledgers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('due_amount', sa.Float(), nullable=False),
    sa.Column('refunded_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['hall_bookings.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_payment_ledgers_temple_id'), 'payment_ledgers', ['temple_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('ledger_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['payment_ledgers.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_temple_id'), 'payment_transactions', ['temple_id'], unique=False)
    op.create_table('refund_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_transaction_id')
    )
    op.add_column('hall_bookings', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hall_bookings', sa.Column('sync_version', sa.Integer(), nullable=True))
    op.add_column('hall_bookings', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('hall_bookings', sa.Column('device_origin', sa.String(), nullable=True))
    op.add_column('hall_bookings', sa.Column('sync_state', sa.String(), nullable=True))
    op.add_column('hall_bookings', sa.Column('payment_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_hall_bookings_created_at'), 'hall_bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_hall_bookings_payment_status'), 'hall_bookings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_hall_bookings_status'), 'hall_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_hall_bookings_sync_version'), 'hall_bookings', ['sync_version'], unique=False)
    op.alter_column('inventory_invoices', 'items_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_invoices', 'items_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('ix_hall_bookings_sync_version'), table_name='hall_bookings')
    op.drop_index(op.f('ix_hall_bookings_status'), table_name='hall_bookings')
    op.drop_index(op.f('ix_hall_bookings_payment_status'), table_name='hall_bookings')
    op.drop_index(op.f('ix_hall_bookings_created_at'), table_name='hall_bookings')
    op.drop_column('hall_bookings', 'payment_status')
    op.drop_column('hall_bookings', 'sync_state')
    op.drop_column('hall_bookings', 'device_origin')
    op.drop_column('hall_bookings', 'version_number')
    op.drop_column('hall_bookings', 'sync_version')
    op.drop_column('hall_bookings', 'last_synced_at')
    op.drop_table('refund_transactions')
    op.drop_index(op.f('ix_payment_transactions_temple_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_payment_ledgers_temple_id'), table_name='payment_ledgers')
    op.drop_table('payment_ledgers')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index(op.f('ix_booking_conflicts_temple_id'), table_name='booking_conflicts')
    op.drop_table('booking_conflicts')
    op.drop_index(op.f('ix_booking_audit_logs_temple_id'), table_name='booking_audit_logs')
    op.drop_index(op.f('ix_booking_audit_logs_booking_id'), table_name='booking_audit_logs')
    op.drop_table('booking_audit_logs')
    op.drop_index(op.f('ix_venue_slots_temple_id'), table_name='venue_slots')
    op.drop_table('venue_slots')
    op.drop_index(op.f('ix_pricing_rules_temple_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_booking_policies_temple_id'), table_name='booking_policies')
    op.drop_table('booking_policies')
    op.drop_index(op.f('ix_booking_holds_temple_id'), table_name='booking_holds')
    op.drop_index(op.f('ix_booking_holds_hall_id'), table_name='booking_holds')
    op.drop_index(op.f('ix_booking_holds_expires_at'), table_name='booking_holds')
    op.drop_index('idx_booking_hold_valid', table_name='booking_holds')
    op.drop_table('booking_holds')
    # ### end Alembic commands ###
