"""add audit integrity verification reports

Revision ID: 35e5d7c23099
Revises: e6ad20f0
Create Date: 2026-06-01 22:48:30.036506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35e5d7c23099'
down_revision: Union[str, Sequence[str], None] = 'e6ad20f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_integrity_verification_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_logs', sa.Integer(), nullable=False),
    sa.Column('failed_logs_count', sa.Integer(), nullable=False),
    sa.Column('failed_log_ids', sa.JSON(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_integrity_verification_reports_temple_id'), 'audit_integrity_verification_reports', ['temple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_integrity_verification_reports_temple_id'), table_name='audit_integrity_verification_reports')
    op.drop_table('audit_integrity_verification_reports')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
