"""align inventory schema with enterprise platform

Revision ID: 4ad52bc2761a
Revises: 4c2b9a1d3f0e
Create Date: 2026-05-16 06:01:20.067390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad52bc2761a'
down_revision: Union[str, Sequence[str], None] = '4c2b9a1d3f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_locations_temple_id'), 'inventory_locations', ['temple_id'], unique=False)
    op.create_table('ritual_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritual_templates_temple_id'), 'ritual_templates', ['temple_id'], unique=False)
    op.create_table('inventory_issue_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'CANCELLED', name='inventoryissuestatus'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['inventory_item_requests.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_issue_sessions_temple_id'), 'inventory_issue_sessions', ['temple_id'], unique=False)
    op.create_table('procurement_grns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('grn_code', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', name='procurementstatus'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_grns_grn_code'), 'procurement_grns', ['grn_code'], unique=True)
    op.create_index(op.f('ix_procurement_grns_temple_id'), 'procurement_grns', ['temple_id'], unique=False)
    op.create_table('donation_inventory_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('donation_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donation_id'], ['donations.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_inventory_mapping_temple_id'), 'donation_inventory_mapping', ['temple_id'], unique=False)
    op.create_table('inventory_reconciliations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('expected_stock', sa.Float(), nullable=False),
    sa.Column('actual_stock', sa.Float(), nullable=False),
    sa.Column('adjustment_qty', sa.Float(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_reconciliations_temple_id'), 'inventory_reconciliations', ['temple_id'], unique=False)
    op.create_table('inventory_stock_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.Enum('PURCHASE', 'ISSUE', 'RETURN', 'DAMAGE', 'WASTAGE', 'TRANSFER', 'DONATION', 'ADJUSTMENT', 'FESTIVAL_ALLOCATION', name='inventorymovementtype'), nullable=False),
    sa.Column('quantity_change', sa.Float(), nullable=False),
    sa.Column('before_stock', sa.Float(), nullable=False),
    sa.Column('after_stock', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stock_ledger_item_id'), 'inventory_stock_ledger', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_stock_ledger_temple_id'), 'inventory_stock_ledger', ['temple_id'], unique=False)
    op.create_index(op.f('ix_inventory_stock_ledger_timestamp'), 'inventory_stock_ledger', ['timestamp'], unique=False)
    op.create_table('ritual_template_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('default_qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ritual_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventory_items', sa.Column('location_id', sa.UUID(), nullable=True))
    op.add_column('inventory_items', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('inventory_items', 'stock',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'min_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_foreign_key(None, 'inventory_items', 'inventory_locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.alter_column('inventory_items', 'min_stock',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'stock',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('inventory_items', 'is_active')
    op.drop_column('inventory_items', 'location_id')
    op.drop_table('ritual_template_items')
    op.drop_index(op.f('ix_inventory_stock_ledger_timestamp'), table_name='inventory_stock_ledger')
    op.drop_index(op.f('ix_inventory_stock_ledger_temple_id'), table_name='inventory_stock_ledger')
    op.drop_index(op.f('ix_inventory_stock_ledger_item_id'), table_name='inventory_stock_ledger')
    op.drop_table('inventory_stock_ledger')
    op.drop_index(op.f('ix_inventory_reconciliations_temple_id'), table_name='inventory_reconciliations')
    op.drop_table('inventory_reconciliations')
    op.drop_index(op.f('ix_donation_inventory_mapping_temple_id'), table_name='donation_inventory_mapping')
    op.drop_table('donation_inventory_mapping')
    op.drop_index(op.f('ix_procurement_grns_temple_id'), table_name='procurement_grns')
    op.drop_index(op.f('ix_procurement_grns_grn_code'), table_name='procurement_grns')
    op.drop_table('procurement_grns')
    op.drop_index(op.f('ix_inventory_issue_sessions_temple_id'), table_name='inventory_issue_sessions')
    op.drop_table('inventory_issue_sessions')
    op.drop_index(op.f('ix_ritual_templates_temple_id'), table_name='ritual_templates')
    op.drop_table('ritual_templates')
    op.drop_index(op.f('ix_inventory_locations_temple_id'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    # ### end Alembic commands ###
