"""Add centralized activity logs and outbox tables

Revision ID: 522c76d941bd
Revises: 25b7b6524acd
Create Date: 2026-05-31 23:07:55.493510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522c76d941bd'
down_revision: Union[str, Sequence[str], None] = '25b7b6524acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('performed_by_role', sa.String(length=100), nullable=False),
    sa.Column('masked_pii', sa.JSON(), nullable=True),
    sa.Column('hashed_pii', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    create_table_kwargs = {}
    if not is_sqlite:
        create_table_kwargs['postgresql_partition_by'] = 'RANGE (created_utc)'

    op.create_table('immutable_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('temple_code', sa.String(length=50), nullable=False),
    sa.Column('tenant_name', sa.String(length=150), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('performed_by_role', sa.String(length=100), nullable=False),
    sa.Column('masked_pii', sa.JSON(), nullable=True),
    sa.Column('hashed_pii', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('browser_info', sa.Text(), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('audit_chain_index', sa.BigInteger(), nullable=False),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_utc'),
    **create_table_kwargs
    )
    op.create_index(op.f('ix_immutable_activity_logs_correlation_id'), 'immutable_activity_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_immutable_activity_logs_created_utc'), 'immutable_activity_logs', ['created_utc'], unique=False)
    op.create_index(op.f('ix_immutable_activity_logs_temple_id'), 'immutable_activity_logs', ['temple_id'], unique=False)

    if not is_sqlite:
        # Create default partition for PostgreSQL partitioned table
        op.execute("CREATE TABLE immutable_activity_logs_default PARTITION OF immutable_activity_logs DEFAULT;")
        
        # Create append-only mutation block trigger and function
        op.execute("""
            CREATE OR REPLACE FUNCTION block_immutable_log_mutation()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Mutation not allowed: immutable_activity_logs is append-only.';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER trg_block_updates_deletes
            BEFORE UPDATE OR DELETE ON immutable_activity_logs
            FOR EACH ROW EXECUTE FUNCTION block_immutable_log_mutation();
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    # ### commands auto generated by Alembic - please adjust! ###
    if not is_sqlite:
        op.execute("DROP TRIGGER IF EXISTS trg_block_updates_deletes ON immutable_activity_logs;")
        op.execute("DROP FUNCTION IF EXISTS block_immutable_log_mutation();")
        op.execute("DROP TABLE IF EXISTS immutable_activity_logs_default;")

    op.drop_index(op.f('ix_immutable_activity_logs_temple_id'), table_name='immutable_activity_logs')
    op.drop_index(op.f('ix_immutable_activity_logs_created_utc'), table_name='immutable_activity_logs')
    op.drop_index(op.f('ix_immutable_activity_logs_correlation_id'), table_name='immutable_activity_logs')
    op.drop_table('immutable_activity_logs')
    op.drop_table('activity_outbox')
    # ### end Alembic commands ###
