"""add_system_rbac_and_onboarding

Revision ID: 5e097ab473a4
Revises: a1b2c3d4e5f6
Create Date: 2026-04-20 18:34:38.310725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e097ab473a4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('system_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['system_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['system_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_sys_role_permission')
    )
    op.create_table('temple_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('alt_contact', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index('idx_temple_requests_domain', 'temple_requests', ['domain'], unique=False)
    op.create_index('idx_temple_requests_status', 'temple_requests', ['status'], unique=False)
    op.create_table('user_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('temple_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_request_id'], ['temple_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_requests_status', 'user_requests', ['status'], unique=False)
    op.create_index('idx_user_requests_temple_request', 'user_requests', ['temple_request_id'], unique=False)
    op.alter_column('addresses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_addresses_active_only'), table_name='addresses', postgresql_where='(is_active = true)')
    op.alter_column('carts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_carts_active_only'), table_name='carts', postgresql_where='(is_active = true)')
    op.alter_column('temples', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_temples_active_only'), table_name='temples', postgresql_where='(is_active = true)')
    op.alter_column('user_temples', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_user_temples_active_only'), table_name='user_temples', postgresql_where='(is_active = true)')
    op.add_column('users', sa.Column('system_role_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_users_active_only'), table_name='users', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_users_system_role_id'), 'users', ['system_role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'system_roles', ['system_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_system_role_id'), table_name='users')
    op.create_index(op.f('ix_users_active_only'), 'users', ['id'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'system_role_id')
    op.create_index(op.f('ix_user_temples_active_only'), 'user_temples', ['id'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('user_temples', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_temples_active_only'), 'temples', ['id'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('temples', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_carts_active_only'), 'carts', ['id'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('carts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_addresses_active_only'), 'addresses', ['id'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('addresses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_user_requests_temple_request', table_name='user_requests')
    op.drop_index('idx_user_requests_status', table_name='user_requests')
    op.drop_table('user_requests')
    op.drop_index('idx_temple_requests_status', table_name='temple_requests')
    op.drop_index('idx_temple_requests_domain', table_name='temple_requests')
    op.drop_table('temple_requests')
    op.drop_table('system_role_permissions')
    op.drop_table('system_roles')
    op.drop_table('system_permissions')
    # ### end Alembic commands ###
