"""create_platform_financial_accounts_and_harden_bank_details

Revision ID: 6422b59e11f6
Revises: daa862090396
Create Date: 2026-06-25 11:05:33.151294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6422b59e11f6'
down_revision: Union[str, Sequence[str], None] = 'daa862090396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_financial_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=150), nullable=False),
    sa.Column('account_identifier', sa.Text(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('online_settlement_ledger', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index('uq_ledger_credit_booking', 'online_settlement_ledger', ['booking_id'], unique=True, postgresql_where=sa.text("entry_type = 'CREDIT'"), sqlite_where=sa.text("entry_type = 'CREDIT'"))
    op.create_unique_constraint(None, 'online_settlement_ledger', ['idempotency_key'])
    op.create_unique_constraint(None, 'ritual_queue', ['booking_id'])
    op.add_column('settlement_batches', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'settlement_batches', ['idempotency_key'])
    # 1. Add version as nullable first to allow existing rows to migrate
    op.add_column('temple_bank_accounts', sa.Column('version', sa.Integer(), nullable=True))
    # 2. Populate default version value for existing rows
    op.execute("UPDATE temple_bank_accounts SET version = 1")
    # 3. Alter column to NOT NULL
    op.alter_column('temple_bank_accounts', 'version', nullable=False)

    op.add_column('temple_bank_accounts', sa.Column('superseded_by', sa.UUID(), nullable=True))
    op.add_column('temple_bank_accounts', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('temple_bank_accounts', sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True))

    # Create Enum Type explicitly in Postgres
    op.execute("CREATE TYPE bankaccountstatus AS ENUM ('PENDING', 'VERIFIED', 'REJECTED', 'SUPERSEDED', 'DISABLED')")

    op.alter_column('temple_bank_accounts', 'verification_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUPERSEDED', 'DISABLED', name='bankaccountstatus'),
               existing_nullable=False,
               postgresql_using="verification_status::bankaccountstatus")
    op.create_foreign_key(None, 'temple_bank_accounts', 'temple_bank_accounts', ['superseded_by'], ['id'])
    
    # Custom Unique Partial Indexes
    op.create_index(
        'uq_active_primary_bank',
        'temple_bank_accounts',
        ['temple_id'],
        unique=True,
        postgresql_where=sa.text("is_active = TRUE AND is_primary = TRUE"),
        sqlite_where=sa.text("is_active = 1 AND is_primary = 1")
    )
    op.create_index(
        'uq_pending_bank_version',
        'temple_bank_accounts',
        ['temple_id'],
        unique=True,
        postgresql_where=sa.text("verification_status = 'PENDING'"),
        sqlite_where=sa.text("verification_status = 'PENDING'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temple_bank_accounts', type_='foreignkey')
    op.alter_column('temple_bank_accounts', 'verification_status',
               existing_type=sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUPERSEDED', 'DISABLED', name='bankaccountstatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('temple_bank_accounts', 'effective_to')
    op.drop_column('temple_bank_accounts', 'effective_from')
    op.drop_column('temple_bank_accounts', 'superseded_by')
    op.drop_column('temple_bank_accounts', 'version')
    op.drop_constraint(None, 'settlement_batches', type_='unique')
    op.drop_column('settlement_batches', 'idempotency_key')
    op.drop_constraint(None, 'ritual_queue', type_='unique')
    op.drop_constraint(None, 'online_settlement_ledger', type_='unique')
    op.drop_index('uq_ledger_credit_booking', table_name='online_settlement_ledger', postgresql_where=sa.text("entry_type = 'CREDIT'"), sqlite_where=sa.text("entry_type = 'CREDIT'"))
    op.drop_column('online_settlement_ledger', 'idempotency_key')
    op.drop_table('platform_financial_accounts')
    op.drop_index('uq_active_primary_bank', table_name='temple_bank_accounts')
    op.drop_index('uq_pending_bank_version', table_name='temple_bank_accounts')
    op.execute("DROP TYPE bankaccountstatus")
    # ### end Alembic commands ###
