"""Add Deity Management tables

Revision ID: 7f0a9d4c2b3a
Revises: 20c869c223e0
Create Date: 2026-05-12 06:24:24.489878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f0a9d4c2b3a'
down_revision: Union[str, Sequence[str], None] = '20c869c223e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deity_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('deity_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='deitystatus'), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deity_master_tenant_id'), 'deity_master', ['tenant_id'], unique=False)
    op.create_table('deity_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deity_id'], ['deity_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_conflict_reports_temple_id'), table_name='conflict_reports')
    op.drop_table('conflict_reports')
    op.drop_index(op.f('idx_sync_checkpoint_device'), table_name='sync_checkpoints')
    op.drop_index(op.f('ix_sync_checkpoints_temple_id'), table_name='sync_checkpoints')
    op.drop_table('sync_checkpoints')
    op.add_column('archana_booking_items', sa.Column('ritual_name_snapshot', sa.String(), nullable=True))
    op.add_column('archana_booking_items', sa.Column('ritual_deity_snapshot', sa.String(), nullable=True))
    op.add_column('archana_booking_items', sa.Column('ritual_duration_snapshot', sa.Integer(), nullable=True))
    op.add_column('archana_booking_items', sa.Column('ritual_version_id', sa.Integer(), nullable=True))
    op.add_column('archana_catalog', sa.Column('deity_id', sa.UUID(), nullable=True))
    op.add_column('archana_catalog', sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ARCHIVED', name='catalogstatus'), nullable=True))
    op.add_column('archana_catalog', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('archana_catalog', sa.Column('requested_by', sa.UUID(), nullable=True))
    op.add_column('archana_catalog', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('archana_catalog', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('archana_catalog', sa.Column('image_url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'archana_catalog', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'archana_catalog', 'users', ['requested_by'], ['id'])
    op.create_foreign_key(None, 'archana_catalog', 'deity_master', ['deity_id'], ['id'])
    op.drop_column('archana_catalog', 'malayalam_name')
    op.drop_column('archana_catalog', 'category')
    op.create_index(op.f('ix_operational_state_audits_temple_id'), 'operational_state_audits', ['temple_id'], unique=False)
    op.alter_column('security_audit_events', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('security_audit_events', 'admin_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_security_audit_events_event_type'), 'security_audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_events_temple_id'), 'security_audit_events', ['temple_id'], unique=False)
    op.alter_column('temple_status_audit', 'old_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('temple_status_audit', 'new_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_temple_status_audit_temple_id'), table_name='temple_status_audit')
    op.create_index(op.f('ix_temple_status_audit_temple_id'), 'temple_status_audit', ['temple_id'], unique=False)
    op.drop_constraint(op.f('temple_status_audit_changed_by_fkey'), 'temple_status_audit', type_='foreignkey')
    op.drop_constraint(op.f('temple_status_audit_temple_id_fkey'), 'temple_status_audit', type_='foreignkey')
    op.create_foreign_key(None, 'temple_status_audit', 'users', ['changed_by'], ['id'])
    op.create_foreign_key(None, 'temple_status_audit', 'temples', ['temple_id'], ['id'])
    op.alter_column('temples', 'operational_state',
               existing_type=postgresql.ENUM('ACTIVE', 'DEACTIVATED', 'SUSPENDED', 'READ_ONLY', 'QUARANTINED', 'INVESTIGATION', 'SYNC_LOCKED', 'OFFLINE_ONLY', 'RECOVERY_MODE', name='templeoperationalstate'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::templeoperationalstate"))
    op.drop_index(op.f('idx_users_approval_status'), table_name='users')
    op.drop_index(op.f('idx_users_temple_id_approval'), table_name='users')
    op.create_foreign_key(None, 'users', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['rejected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('idx_users_temple_id_approval'), 'users', ['temple_id', 'approval_status'], unique=False)
    op.create_index(op.f('idx_users_approval_status'), 'users', ['approval_status'], unique=False)
    op.alter_column('temples', 'operational_state',
               existing_type=postgresql.ENUM('ACTIVE', 'DEACTIVATED', 'SUSPENDED', 'READ_ONLY', 'QUARANTINED', 'INVESTIGATION', 'SYNC_LOCKED', 'OFFLINE_ONLY', 'RECOVERY_MODE', name='templeoperationalstate'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::templeoperationalstate"))
    op.drop_constraint(None, 'temple_status_audit', type_='foreignkey')
    op.drop_constraint(None, 'temple_status_audit', type_='foreignkey')
    op.create_foreign_key(op.f('temple_status_audit_temple_id_fkey'), 'temple_status_audit', 'temples', ['temple_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('temple_status_audit_changed_by_fkey'), 'temple_status_audit', 'users', ['changed_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_temple_status_audit_temple_id'), table_name='temple_status_audit')
    op.create_index(op.f('idx_temple_status_audit_temple_id'), 'temple_status_audit', ['temple_id'], unique=False)
    op.alter_column('temple_status_audit', 'new_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('temple_status_audit', 'old_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_security_audit_events_temple_id'), table_name='security_audit_events')
    op.drop_index(op.f('ix_security_audit_events_event_type'), table_name='security_audit_events')
    op.alter_column('security_audit_events', 'admin_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('security_audit_events', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_operational_state_audits_temple_id'), table_name='operational_state_audits')
    op.add_column('archana_catalog', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('archana_catalog', sa.Column('malayalam_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'archana_catalog', type_='foreignkey')
    op.drop_constraint(None, 'archana_catalog', type_='foreignkey')
    op.drop_constraint(None, 'archana_catalog', type_='foreignkey')
    op.drop_column('archana_catalog', 'image_url')
    op.drop_column('archana_catalog', 'rejection_reason')
    op.drop_column('archana_catalog', 'approved_by')
    op.drop_column('archana_catalog', 'requested_by')
    op.drop_column('archana_catalog', 'version')
    op.drop_column('archana_catalog', 'status')
    op.drop_column('archana_catalog', 'deity_id')
    op.drop_column('archana_booking_items', 'ritual_version_id')
    op.drop_column('archana_booking_items', 'ritual_duration_snapshot')
    op.drop_column('archana_booking_items', 'ritual_deity_snapshot')
    op.drop_column('archana_booking_items', 'ritual_name_snapshot')
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('temple_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], name=op.f('sync_checkpoints_temple_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_checkpoints_pkey'))
    )
    op.create_index(op.f('ix_sync_checkpoints_temple_id'), 'sync_checkpoints', ['temple_id'], unique=False)
    op.create_index(op.f('idx_sync_checkpoint_device'), 'sync_checkpoints', ['temple_id', 'device_id'], unique=True)
    op.create_table('conflict_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('temple_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resolution_strategy', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('conflict_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('conflict_reports_resolved_by_fkey')),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], name=op.f('conflict_reports_temple_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conflict_reports_pkey'))
    )
    op.create_index(op.f('ix_conflict_reports_temple_id'), 'conflict_reports', ['temple_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('processed_events_pkey'))
    )
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=True)
    op.drop_table('deity_audit')
    op.drop_index(op.f('ix_deity_master_tenant_id'), table_name='deity_master')
    op.drop_table('deity_master')
    # ### end Alembic commands ###
