"""Add normalized_name and UniqueConstraint to DeityMaster

Revision ID: b2ad685ddf72
Revises: 7f0a9d4c2b3a
Create Date: 2026-05-12 06:40:12.214633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ad685ddf72'
down_revision: Union[str, Sequence[str], None] = '7f0a9d4c2b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deity_master', sa.Column('normalized_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_deity_master_normalized_name'), 'deity_master', ['normalized_name'], unique=False)
    op.create_unique_constraint('uq_deity_name_per_tenant', 'deity_master', ['tenant_id', 'deity_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_deity_name_per_tenant', 'deity_master', type_='unique')
    op.drop_index(op.f('ix_deity_master_normalized_name'), table_name='deity_master')
    op.drop_column('deity_master', 'normalized_name')
    # ### end Alembic commands ###
