"""add_idempotency_and_groups

Revision ID: bb4828bc10ec
Revises: 0f99a02d05d3
Create Date: 2026-05-13 06:47:46.963521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4828bc10ec'
down_revision: Union[str, Sequence[str], None] = '0f99a02d05d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    # Handle Enum type 'queuestatus' - add 'SKIPPED' if it doesn't exist
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid WHERE t.typname = 'queuestatus' AND e.enumlabel = 'SKIPPED') THEN ALTER TYPE queuestatus ADD VALUE 'SKIPPED'; END IF; END $$;")
    
    # Create completionmode enum
    completion_mode = postgresql.ENUM('MANUAL', 'AUTO', name='completionmode')
    completion_mode.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archana_execution_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('ritual_name_snapshot', sa.String(), nullable=True),
    sa.Column('started_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_completion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'SKIPPED', 'SYNC_PENDING', name='queuestatus', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archana_execution_groups_temple_id'), 'archana_execution_groups', ['temple_id'], unique=False)
    op.add_column('archana_executions', sa.Column('completion_mode', postgresql.ENUM('MANUAL', 'AUTO', name='completionmode', create_type=False), nullable=True))
    op.add_column('archana_executions', sa.Column('execution_group_id', sa.UUID(), nullable=True))
    op.add_column('archana_executions', sa.Column('version', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_archana_executions_execution_group_id'), 'archana_executions', ['execution_group_id'], unique=False)
    op.create_foreign_key(None, 'archana_executions', 'archana_execution_groups', ['execution_group_id'], ['id'])
    op.add_column('enterprise_archana_bookings', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_enterprise_archana_bookings_idempotency_key'), 'enterprise_archana_bookings', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enterprise_archana_bookings_idempotency_key'), table_name='enterprise_archana_bookings')
    op.drop_column('enterprise_archana_bookings', 'idempotency_key')
    op.drop_constraint(None, 'archana_executions', type_='foreignkey')
    op.drop_index(op.f('ix_archana_executions_execution_group_id'), table_name='archana_executions')
    op.drop_column('archana_executions', 'version')
    op.drop_column('archana_executions', 'execution_group_id')
    op.drop_column('archana_executions', 'completion_mode')
    op.drop_index(op.f('ix_archana_execution_groups_temple_id'), table_name='archana_execution_groups')
    op.drop_table('archana_execution_groups')
    # ### end Alembic commands ###
