"""Schema alignment pass

Revision ID: cf49bc934db9
Revises: 0017929bb170
Create Date: 2026-04-26 13:21:33.064394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf49bc934db9'
down_revision: Union[str, Sequence[str], None] = '0017929bb170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temple_code_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('last_val', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_code_sequences_date'), 'temple_code_sequences', ['date'], unique=True)
    op.create_table('temple_profile_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('opening_time', sa.String(), nullable=True),
    sa.Column('closing_time', sa.String(), nullable=True),
    sa.Column('live_stream_url', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_profile_drafts_temple_id'), 'temple_profile_drafts', ['temple_id'], unique=False)
    op.add_column('archana_bookings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('archana_bookings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_archana_bookings_is_active'), 'archana_bookings', ['is_active'], unique=False)
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.drop_column('guest_bookings', 'created_at')
    op.drop_column('guest_bookings', 'amount')
    op.drop_column('guest_bookings', 'booking_date')
    op.drop_column('guest_bookings', 'status')
    op.drop_column('guest_bookings', 'notes')
    op.drop_column('guest_bookings', 'updated_at')
    op.add_column('halls', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('halls', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_halls_is_active'), 'halls', ['is_active'], unique=False)
    op.drop_index(op.f('idx_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.add_column('poojas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_poojas_is_active'), 'poojas', ['is_active'], unique=False)
    op.alter_column('staff_invites', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('staff_invites_token_key'), 'staff_invites', type_='unique')
    op.create_index(op.f('ix_staff_invites_email'), 'staff_invites', ['email'], unique=False)
    op.create_index(op.f('ix_staff_invites_token'), 'staff_invites', ['token'], unique=True)
    op.add_column('temple_requests', sa.Column('rejected_by', sa.UUID(), nullable=True))
    op.add_column('temple_requests', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'temple_requests', 'users', ['rejected_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temple_requests', type_='foreignkey')
    op.drop_column('temple_requests', 'rejected_at')
    op.drop_column('temple_requests', 'rejected_by')
    op.drop_index(op.f('ix_staff_invites_token'), table_name='staff_invites')
    op.drop_index(op.f('ix_staff_invites_email'), table_name='staff_invites')
    op.create_unique_constraint(op.f('staff_invites_token_key'), 'staff_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('staff_invites', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_poojas_is_active'), table_name='poojas')
    op.drop_column('poojas', 'deleted_at')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_unique_constraint(op.f('password_reset_tokens_token_key'), 'password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.drop_index(op.f('ix_halls_is_active'), table_name='halls')
    op.drop_column('halls', 'deleted_at')
    op.drop_column('halls', 'is_active')
    op.add_column('guest_bookings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('guest_bookings', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('guest_bookings', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guest_bookings', sa.Column('booking_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('guest_bookings', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('guest_bookings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_column('employees', 'deleted_at')
    op.drop_column('employees', 'is_active')
    op.drop_index(op.f('ix_archana_bookings_is_active'), table_name='archana_bookings')
    op.drop_column('archana_bookings', 'deleted_at')
    op.drop_column('archana_bookings', 'is_active')
    op.drop_index(op.f('ix_temple_profile_drafts_temple_id'), table_name='temple_profile_drafts')
    op.drop_table('temple_profile_drafts')
    op.drop_index(op.f('ix_temple_code_sequences_date'), table_name='temple_code_sequences')
    op.drop_table('temple_code_sequences')
    # ### end Alembic commands ###
