"""add_sprint1_entities

Revision ID: d5460663d845
Revises: add_website_publication_snapshots
Create Date: 2026-06-08 11:55:03.233607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5460663d845'
down_revision: Union[str, Sequence[str], None] = 'add_website_publication_snapshots'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_advertisements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_global_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_global_settings_key'), 'platform_global_settings', ['key'], unique=True)
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=True)
    op.create_table('conflict_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('resolution_strategy', sa.String(), nullable=False),
    sa.Column('conflict_details', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_reports_temple_id'), 'conflict_reports', ['temple_id'], unique=False)
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_checkpoint_device', 'sync_checkpoints', ['temple_id', 'device_id'], unique=True)
    op.create_index(op.f('ix_sync_checkpoints_temple_id'), 'sync_checkpoints', ['temple_id'], unique=False)
    op.create_table('temple_advertisements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_temple_ads_active', 'temple_advertisements', ['temple_id', 'start_date', 'end_date'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index(op.f('ix_temple_advertisements_temple_id'), 'temple_advertisements', ['temple_id'], unique=False)
    op.create_table('advertisement_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advertisement_type', sa.String(length=20), nullable=False),
    sa.Column('platform_advertisement_id', sa.UUID(), nullable=True),
    sa.Column('temple_advertisement_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(advertisement_type = 'PLATFORM' AND platform_advertisement_id IS NOT NULL AND temple_advertisement_id IS NULL) OR (advertisement_type = 'TEMPLE' AND temple_advertisement_id IS NOT NULL AND platform_advertisement_id IS NULL)", name='chk_ad_analytics_owner'),
    sa.ForeignKeyConstraint(['platform_advertisement_id'], ['platform_advertisements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_advertisement_id'], ['temple_advertisements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ad_analytics_agg', 'advertisement_analytics', ['platform_advertisement_id', 'temple_advertisement_id', 'event_type', 'created_at'], unique=False)
    op.create_table('temple_follower_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('festival_enabled', sa.Boolean(), nullable=False),
    sa.Column('announcement_enabled', sa.Boolean(), nullable=False),
    sa.Column('event_enabled', sa.Boolean(), nullable=False),
    sa.Column('pooja_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('custom_categories', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['temple_followers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_follower_preferences_follower_id'), 'temple_follower_preferences', ['follower_id'], unique=True)
    op.create_table('service_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('source_service_id', sa.UUID(), nullable=False),
    sa.Column('recommended_service_id', sa.UUID(), nullable=True),
    sa.Column('recommended_product_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(recommended_service_id IS NOT NULL AND recommended_product_id IS NULL) OR (recommended_product_id IS NOT NULL AND recommended_service_id IS NULL)', name='chk_recommendation_target'),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_service_id'], ['temple_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_service_id'], ['temple_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_recommendations_lookup', 'service_recommendations', ['temple_id', 'source_service_id'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index(op.f('ix_service_recommendations_temple_id'), 'service_recommendations', ['temple_id'], unique=False)
    op.add_column('guest_bookings', sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('guest_bookings', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('guest_bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('guest_bookings', sa.Column('notification_mode', sa.Enum('PUSH', 'EMAIL', 'SMS', name='notificationmode'), nullable=False))
    op.add_column('guest_bookings', sa.Column('notification_destination', sa.String(), nullable=True))
    op.add_column('guest_bookings', sa.Column('dakshina_amount', sa.Float(), nullable=False))
    op.add_column('guest_bookings', sa.Column('booking_source', sa.Enum('WEB_PUBLIC', 'MOBILE_APP', 'COUNTER', 'ADMIN', name='bookingsource'), nullable=False))
    op.add_column('guest_bookings', sa.Column('booking_metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False))
    op.add_column('service_bookings', sa.Column('notification_mode', sa.Enum('PUSH', 'EMAIL', 'SMS', name='notificationmode'), nullable=False))
    op.add_column('service_bookings', sa.Column('notification_destination', sa.String(), nullable=True))
    op.add_column('service_bookings', sa.Column('dakshina_amount', sa.Float(), nullable=False))
    op.add_column('service_bookings', sa.Column('booking_source', sa.Enum('WEB_PUBLIC', 'MOBILE_APP', 'COUNTER', 'ADMIN', name='bookingsource'), nullable=False))
    op.add_column('service_bookings', sa.Column('booking_metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False))
    op.add_column('temple_followers', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temple_followers', 'is_active')
    op.drop_column('service_bookings', 'booking_metadata')
    op.drop_column('service_bookings', 'booking_source')
    op.drop_column('service_bookings', 'dakshina_amount')
    op.drop_column('service_bookings', 'notification_destination')
    op.drop_column('service_bookings', 'notification_mode')
    op.drop_column('guest_bookings', 'booking_metadata')
    op.drop_column('guest_bookings', 'booking_source')
    op.drop_column('guest_bookings', 'dakshina_amount')
    op.drop_column('guest_bookings', 'notification_destination')
    op.drop_column('guest_bookings', 'notification_mode')
    op.drop_column('guest_bookings', 'notes')
    op.drop_column('guest_bookings', 'amount')
    op.drop_column('guest_bookings', 'booking_date')
    op.drop_index(op.f('ix_service_recommendations_temple_id'), table_name='service_recommendations')
    op.drop_index('idx_service_recommendations_lookup', table_name='service_recommendations', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('service_recommendations')
    op.drop_index(op.f('ix_temple_follower_preferences_follower_id'), table_name='temple_follower_preferences')
    op.drop_table('temple_follower_preferences')
    op.drop_index('idx_ad_analytics_agg', table_name='advertisement_analytics')
    op.drop_table('advertisement_analytics')
    op.drop_index(op.f('ix_temple_advertisements_temple_id'), table_name='temple_advertisements')
    op.drop_index('idx_temple_ads_active', table_name='temple_advertisements', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('temple_advertisements')
    op.drop_index(op.f('ix_sync_checkpoints_temple_id'), table_name='sync_checkpoints')
    op.drop_index('idx_sync_checkpoint_device', table_name='sync_checkpoints')
    op.drop_table('sync_checkpoints')
    op.drop_index(op.f('ix_conflict_reports_temple_id'), table_name='conflict_reports')
    op.drop_table('conflict_reports')
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_platform_global_settings_key'), table_name='platform_global_settings')
    op.drop_table('platform_global_settings')
    op.drop_table('platform_advertisements')
    # ### end Alembic commands ###
