"""add_sprint3_entities

Revision ID: d912501e7d00
Revises: 2f307da424dd
Create Date: 2026-06-08 13:07:09.995356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd912501e7d00'
down_revision: Union[str, Sequence[str], None] = '2f307da424dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_name IN ('BOOK_POOJA_CLICK', 'OFFERING_CLICK', 'STORE_CLICK', 'FOLLOW_CLICK', 'AD_CLICK', 'RECOMMENDATION_CLICK', 'CHECKOUT_STARTED', 'CHECKOUT_COMPLETED')", name='chk_portal_event_name'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portal_analytics_lookup', 'portal_analytics_events', ['temple_id', 'event_name', 'created_at'], unique=False)
    
    # Batch alter cart_items
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_cart_items_product', 'store_products', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_check_constraint(
            'chk_cart_item_target',
            'service_id IS NOT NULL OR product_id IS NOT NULL'
        )

    # Batch alter platform_advertisements
    with op.batch_alter_table('platform_advertisements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=20), nullable=False, server_default='IMAGE'))
        batch_op.create_check_constraint(
            'chk_platform_ad_media_type',
            "media_type IN ('IMAGE', 'CAROUSEL')"
        )

    # Batch alter service_recommendations
    with op.batch_alter_table('service_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_product_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_source_type', sa.String(length=20), nullable=False, server_default='SERVICE'))
        batch_op.alter_column('source_service_id', existing_type=sa.TEXT(), nullable=True)
        batch_op.create_foreign_key('fk_recommendations_source_product', 'store_products', ['source_product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_check_constraint(
            'chk_recommendation_source',
            '(source_service_id IS NOT NULL AND source_product_id IS NULL) OR (source_product_id IS NOT NULL AND source_service_id IS NULL)'
        )

    op.create_index('idx_product_recommendations_lookup', 'service_recommendations', ['temple_id', 'source_product_id'], unique=False, postgresql_where=sa.text('is_active = TRUE'))

    # Batch alter temple_advertisements
    with op.batch_alter_table('temple_advertisements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=20), nullable=False, server_default='IMAGE'))
        batch_op.create_check_constraint(
            'chk_temple_ad_media_type',
            "media_type IN ('IMAGE', 'CAROUSEL')"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temple_advertisements', schema=None) as batch_op:
        batch_op.drop_constraint('chk_temple_ad_media_type', type_='check')
        batch_op.drop_column('media_type')

    op.drop_index('idx_product_recommendations_lookup', table_name='service_recommendations', postgresql_where=sa.text('is_active = TRUE'))

    with op.batch_alter_table('service_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('chk_recommendation_source', type_='check')
        batch_op.drop_constraint('fk_recommendations_source_product', type_='foreignkey')
        batch_op.alter_column('source_service_id', existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column('recommendation_source_type')
        batch_op.drop_column('source_product_id')

    with op.batch_alter_table('platform_advertisements', schema=None) as batch_op:
        batch_op.drop_constraint('chk_platform_ad_media_type', type_='check')
        batch_op.drop_column('media_type')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('chk_cart_item_target', type_='check')
        batch_op.drop_constraint('fk_cart_items_product', type_='foreignkey')
        batch_op.drop_column('product_id')

    op.drop_index('idx_portal_analytics_lookup', table_name='portal_analytics_events')
    op.drop_table('portal_analytics_events')
    # ### end Alembic commands ###
