"""add_online_booking_settlement_and_notifications

Revision ID: daa862090396
Revises: 27e063926090
Create Date: 2026-06-23 12:47:12.999412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa862090396'
down_revision: Union[str, Sequence[str], None] = '27e063926090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_delivery_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('outbox_event_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_address', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_delivery_logs_outbox_event_id'), 'notification_delivery_logs', ['outbox_event_id'], unique=False)
    op.create_index(op.f('ix_notification_delivery_logs_temple_id'), 'notification_delivery_logs', ['temple_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=True),
    sa.Column('event_code', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temple_id', 'event_code', 'channel', 'language', name='uq_notification_template')
    )
    op.create_table('temple_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('account_number_enc', sa.Text(), nullable=False),
    sa.Column('ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('cancelled_cheque_url', sa.Text(), nullable=True),
    sa.Column('proof_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_bank_accounts_temple_id'), 'temple_bank_accounts', ['temple_id'], unique=False)
    op.create_table('settlement_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('batch_ref', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('total_archana_amount', sa.Float(), nullable=False),
    sa.Column('total_refunds', sa.Float(), nullable=False),
    sa.Column('net_payout_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_method', sa.String(length=20), nullable=True),
    sa.Column('payout_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('payout_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['temple_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_ref'),
    sa.UniqueConstraint('temple_id', 'period_start', 'period_end', name='uq_temple_period')
    )
    op.create_index(op.f('ix_settlement_batches_temple_id'), 'settlement_batches', ['temple_id'], unique=False)
    op.create_table('online_settlement_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('archana_amount', sa.Float(), nullable=False),
    sa.Column('temple_net_amount', sa.Float(), nullable=False),
    sa.Column('gross_convenience_fee', sa.Float(), nullable=False),
    sa.Column('taxable_fee', sa.Float(), nullable=False),
    sa.Column('gst_component', sa.Float(), nullable=False),
    sa.Column('cgst_component', sa.Float(), nullable=False),
    sa.Column('sgst_component', sa.Float(), nullable=False),
    sa.Column('gateway_fee', sa.Float(), nullable=True),
    sa.Column('gateway_tax', sa.Float(), nullable=True),
    sa.Column('net_platform_revenue', sa.Float(), nullable=False),
    sa.Column('total_charged_to_devotee', sa.Float(), nullable=False),
    sa.Column('settlement_batch_id', sa.UUID(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['enterprise_archana_bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['archana_booking_payments.id'], ),
    sa.ForeignKeyConstraint(['settlement_batch_id'], ['settlement_batches.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_online_settlement_ledger_is_settled'), 'online_settlement_ledger', ['is_settled'], unique=False)
    op.create_index(op.f('ix_online_settlement_ledger_settlement_batch_id'), 'online_settlement_ledger', ['settlement_batch_id'], unique=False)
    op.create_index(op.f('ix_online_settlement_ledger_temple_id'), 'online_settlement_ledger', ['temple_id'], unique=False)
    op.create_table('settlement_batch_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['settlement_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['online_settlement_ledger.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ledger_entry_id')
    )
    op.add_column('archana_booking_payments', sa.Column('gateway_payment_id', sa.String(length=100), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('gateway_order_id', sa.String(length=100), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('gateway_method', sa.String(length=30), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('gateway_fee', sa.Float(), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('gateway_tax', sa.Float(), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('archana_amount', sa.Float(), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('convenience_fee', sa.Float(), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('total_amount_charged', sa.Float(), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('webhook_payload', sa.JSON(), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('webhook_received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('archana_booking_payments', sa.Column('settlement_status', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'archana_booking_payments', ['gateway_payment_id'])
    op.add_column('archana_catalog', sa.Column('is_online_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('archana_catalog', sa.Column('available_prasadam_modes', sa.JSON(), nullable=True))
    op.add_column('archana_catalog', sa.Column('completion_mode', sa.String(length=30), nullable=True))
    op.add_column('archana_refunds', sa.Column('gateway_refund_id', sa.String(length=100), nullable=True))
    op.add_column('archana_refunds', sa.Column('gateway_refund_status', sa.String(length=50), nullable=True))
    op.add_column('archana_refunds', sa.Column('refund_initiated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('archana_refunds', sa.Column('refund_settled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('archana_refunds', sa.Column('archana_refund_amount', sa.Float(), nullable=True))
    op.add_column('archana_refunds', sa.Column('fee_refund_amount', sa.Float(), nullable=True))
    op.add_column('archana_refunds', sa.Column('total_refund_amount', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'archana_refunds', ['gateway_refund_id'])
    op.add_column('enterprise_archana_bookings', sa.Column('devotee_user_id', sa.UUID(), nullable=True))
    op.add_column('enterprise_archana_bookings', sa.Column('online_status', sa.String(length=30), nullable=True))
    op.add_column('enterprise_archana_bookings', sa.Column('booking_channel', sa.String(length=20), nullable=True))
    op.add_column('enterprise_archana_bookings', sa.Column('gateway_order_id', sa.String(length=100), nullable=True))
    op.add_column('enterprise_archana_bookings', sa.Column('payment_expiry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enterprise_archana_bookings', sa.Column('total_payable', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'enterprise_archana_bookings', ['gateway_order_id'])
    op.create_foreign_key(None, 'enterprise_archana_bookings', 'users', ['devotee_user_id'], ['id'])
    op.add_column('temples', sa.Column('is_settlement_eligible', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('temples', sa.Column('settlement_hold_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temples', 'settlement_hold_reason')
    op.drop_column('temples', 'is_settlement_eligible')
    op.drop_constraint(None, 'enterprise_archana_bookings', type_='foreignkey')
    op.drop_constraint(None, 'enterprise_archana_bookings', type_='unique')
    op.drop_column('enterprise_archana_bookings', 'total_payable')
    op.drop_column('enterprise_archana_bookings', 'payment_expiry_at')
    op.drop_column('enterprise_archana_bookings', 'gateway_order_id')
    op.drop_column('enterprise_archana_bookings', 'booking_channel')
    op.drop_column('enterprise_archana_bookings', 'online_status')
    op.drop_column('enterprise_archana_bookings', 'devotee_user_id')
    op.drop_constraint(None, 'archana_refunds', type_='unique')
    op.drop_column('archana_refunds', 'total_refund_amount')
    op.drop_column('archana_refunds', 'fee_refund_amount')
    op.drop_column('archana_refunds', 'archana_refund_amount')
    op.drop_column('archana_refunds', 'refund_settled_at')
    op.drop_column('archana_refunds', 'refund_initiated_at')
    op.drop_column('archana_refunds', 'gateway_refund_status')
    op.drop_column('archana_refunds', 'gateway_refund_id')
    op.drop_column('archana_catalog', 'completion_mode')
    op.drop_column('archana_catalog', 'available_prasadam_modes')
    op.drop_column('archana_catalog', 'is_online_enabled')
    op.drop_constraint(None, 'archana_booking_payments', type_='unique')
    op.drop_column('archana_booking_payments', 'settlement_status')
    op.drop_column('archana_booking_payments', 'webhook_received_at')
    op.drop_column('archana_booking_payments', 'webhook_payload')
    op.drop_column('archana_booking_payments', 'total_amount_charged')
    op.drop_column('archana_booking_payments', 'convenience_fee')
    op.drop_column('archana_booking_payments', 'archana_amount')
    op.drop_column('archana_booking_payments', 'gateway_tax')
    op.drop_column('archana_booking_payments', 'gateway_fee')
    op.drop_column('archana_booking_payments', 'gateway_method')
    op.drop_column('archana_booking_payments', 'gateway_order_id')
    op.drop_column('archana_booking_payments', 'gateway_payment_id')
    op.drop_table('settlement_batch_items')
    op.drop_index(op.f('ix_online_settlement_ledger_temple_id'), table_name='online_settlement_ledger')
    op.drop_index(op.f('ix_online_settlement_ledger_settlement_batch_id'), table_name='online_settlement_ledger')
    op.drop_index(op.f('ix_online_settlement_ledger_is_settled'), table_name='online_settlement_ledger')
    op.drop_table('online_settlement_ledger')
    op.drop_index(op.f('ix_settlement_batches_temple_id'), table_name='settlement_batches')
    op.drop_table('settlement_batches')
    op.drop_index(op.f('ix_temple_bank_accounts_temple_id'), table_name='temple_bank_accounts')
    op.drop_table('temple_bank_accounts')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_notification_delivery_logs_temple_id'), table_name='notification_delivery_logs')
    op.drop_index(op.f('ix_notification_delivery_logs_outbox_event_id'), table_name='notification_delivery_logs')
    op.drop_table('notification_delivery_logs')
    # ### end Alembic commands ###
