"""digital_experience

Revision ID: db8df6465e0a
Revises: 35e5d7c23099
Create Date: 2026-06-04 11:58:39.009693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db8df6465e0a'
down_revision: Union[str, Sequence[str], None] = '35e5d7c23099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temple_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'COMPLETED', name='activity_status_enum'), nullable=False),
    sa.Column('livestream_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_activities_temple_id'), 'temple_activities', ['temple_id'], unique=False)
    
    op.create_table('temple_announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_announcements_temple_id'), 'temple_announcements', ['temple_id'], unique=False)
    
    op.create_table('temple_website_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('theme_name', sa.String(), nullable=False),
    sa.Column('primary_color', sa.String(), nullable=False),
    sa.Column('secondary_color', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('hero_layout', sa.String(), nullable=False),
    sa.Column('section_order', sa.JSON(), nullable=False),
    sa.Column('enable_mantras', sa.Boolean(), nullable=False),
    sa.Column('enable_festivals', sa.Boolean(), nullable=False),
    sa.Column('enable_donations', sa.Boolean(), nullable=False),
    sa.Column('enable_hall_booking', sa.Boolean(), nullable=False),
    sa.Column('enable_store', sa.Boolean(), nullable=False),
    sa.Column('seo_keywords', sa.String(), nullable=True),
    sa.Column('og_image_url', sa.String(), nullable=True),
    sa.Column('hero_title', sa.String(), nullable=True),
    sa.Column('hero_subtitle', sa.String(), nullable=True),
    sa.Column('notice_board_content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temple_website_settings_temple_id'), 'temple_website_settings', ['temple_id'], unique=True)
    
    # Create image_category_enum type explicitly
    image_category_enum = postgresql.ENUM('HERO_DESKTOP', 'HERO_MOBILE', 'GALLERY', 'DEITY', 'FESTIVAL', 'FACILITY', 'OTHER', name='image_category_enum')
    image_category_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('temple_images', sa.Column('category', sa.Enum('HERO_DESKTOP', 'HERO_MOBILE', 'GALLERY', 'DEITY', 'FESTIVAL', 'FACILITY', 'OTHER', name='image_category_enum'), nullable=False, server_default='GALLERY'))
    op.add_column('temple_profile_drafts', sa.Column('main_deity', sa.String(), nullable=True))
    op.add_column('temple_profile_drafts', sa.Column('deities', sa.JSON(), nullable=True))
    op.add_column('temple_profile_drafts', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('temple_profile_drafts', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('temple_profile_drafts', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('temple_profile_drafts', sa.Column('twitter_url', sa.String(), nullable=True))
    op.add_column('temple_profile_drafts', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('temple_profile_drafts', sa.Column('festivals_description', sa.Text(), nullable=True))
    op.add_column('temple_profiles', sa.Column('main_deity', sa.String(), nullable=True))
    op.add_column('temple_profiles', sa.Column('deities', sa.JSON(), nullable=True))
    op.add_column('temple_profiles', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('temple_profiles', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('temple_profiles', sa.Column('youtube_url', sa.String(), nullable=True))
    op.add_column('temple_profiles', sa.Column('twitter_url', sa.String(), nullable=True))
    op.add_column('temple_profiles', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('temple_profiles', sa.Column('festivals_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temple_profiles', 'festivals_description')
    op.drop_column('temple_profiles', 'website_url')
    op.drop_column('temple_profiles', 'twitter_url')
    op.drop_column('temple_profiles', 'youtube_url')
    op.drop_column('temple_profiles', 'instagram_url')
    op.drop_column('temple_profiles', 'facebook_url')
    op.drop_column('temple_profiles', 'deities')
    op.drop_column('temple_profiles', 'main_deity')
    op.drop_column('temple_profile_drafts', 'festivals_description')
    op.drop_column('temple_profile_drafts', 'website_url')
    op.drop_column('temple_profile_drafts', 'twitter_url')
    op.drop_column('temple_profile_drafts', 'youtube_url')
    op.drop_column('temple_profile_drafts', 'instagram_url')
    op.drop_column('temple_profile_drafts', 'facebook_url')
    op.drop_column('temple_profile_drafts', 'deities')
    op.drop_column('temple_profile_drafts', 'main_deity')
    op.drop_column('temple_images', 'category')
    op.drop_index(op.f('ix_temple_website_settings_temple_id'), table_name='temple_website_settings')
    op.drop_table('temple_website_settings')
    op.drop_index(op.f('ix_temple_announcements_temple_id'), table_name='temple_announcements')
    op.drop_table('temple_announcements')
    op.drop_index(op.f('ix_temple_activities_temple_id'), table_name='temple_activities')
    op.drop_table('temple_activities')

    # Drop custom ENUM types explicitly
    image_category_enum = postgresql.ENUM('HERO_DESKTOP', 'HERO_MOBILE', 'GALLERY', 'DEITY', 'FESTIVAL', 'FACILITY', 'OTHER', name='image_category_enum')
    image_category_enum.drop(op.get_bind(), checkfirst=True)

    activity_status_enum = postgresql.ENUM('UPCOMING', 'ACTIVE', 'COMPLETED', name='activity_status_enum')
    activity_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
