"""Stabilization Audit

Revision ID: fddf3e83bce9
Revises: 
Create Date: 2026-04-17 16:51:37.986919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddf3e83bce9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_is_active'), 'addresses', ['is_active'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_temple_id'), 'approval_requests', ['temple_id'], unique=False)
    
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_is_active'), 'carts', ['is_active'], unique=False)
    op.create_index(op.f('ix_carts_temple_id'), 'carts', ['temple_id'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    
    op.create_table('change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('target_version', sa.Integer(), nullable=True),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_change_requests_entity', 'change_requests', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_change_requests_status', 'change_requests', ['status'], unique=False)
    op.create_index('idx_change_requests_temple', 'change_requests', ['temple_id'], unique=False)
    op.create_index(op.f('ix_change_requests_temple_id'), 'change_requests', ['temple_id'], unique=False)
    
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_temple_id'), 'notifications', ['temple_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    
    op.create_table('temple_followers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'temple_id', name='uq_temple_follower')
    )
    
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['temple_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('guest_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('temple_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(), nullable=False),
    sa.Column('guest_phone', sa.String(), nullable=False),
    sa.Column('guest_email', sa.String(), nullable=True),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['temple_services.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_bookings_temple_id'), 'guest_bookings', ['temple_id'], unique=False)
    
    with op.batch_alter_table('audit_logs') as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('module_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('action_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('old_value', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approval_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_audit_logs_approval_requests', 'approval_requests', ['approval_id'], ['id'])
    
    # SAFE ADDITION OF NON-NULLABLE 'version' COLUMNS
    with op.batch_alter_table('employees') as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE employees SET version = 1 WHERE version IS NULL")
    with op.batch_alter_table('employees') as batch_op:
        batch_op.alter_column('version', nullable=False)
    
    with op.batch_alter_table('halls') as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE halls SET version = 1 WHERE version IS NULL")
    with op.batch_alter_table('halls') as batch_op:
        batch_op.alter_column('version', nullable=False)
    
    with op.batch_alter_table('inventory_items') as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE inventory_items SET version = 1 WHERE version IS NULL")
    with op.batch_alter_table('inventory_items') as batch_op:
        batch_op.alter_column('version', nullable=False)
    
    with op.batch_alter_table('payments') as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    
    # SOFT DELETE COLUMNS FOR TEMPLES
    with op.batch_alter_table('temples') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
    op.execute("UPDATE temples SET is_active = TRUE, version = 1 WHERE is_active IS NULL OR version IS NULL")
    with op.batch_alter_table('temples') as batch_op:
        batch_op.alter_column('is_active', nullable=False)
        batch_op.alter_column('version', nullable=False)
    op.create_index(op.f('ix_temples_is_active'), 'temples', ['is_active'], unique=False)
    
    # SOFT DELETE COLUMNS FOR USER_TEMPLES
    with op.batch_alter_table('user_temples') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE user_temples SET is_active = TRUE WHERE is_active IS NULL")
    with op.batch_alter_table('user_temples') as batch_op:
        batch_op.alter_column('is_active', nullable=False)
    op.create_index(op.f('ix_user_temples_is_active'), 'user_temples', ['is_active'], unique=False)
    
    # USER SCHEMA HARDENING
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='ACTIVE', nullable=True))
        batch_op.add_column(sa.Column('otp_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_active', nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('status')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        
    op.drop_index(op.f('ix_user_temples_is_active'), table_name='user_temples')
    with op.batch_alter_table('user_temples') as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')
        
    op.drop_index(op.f('ix_temples_is_active'), table_name='temples')
    with op.batch_alter_table('temples') as batch_op:
        batch_op.drop_column('version')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')
        
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    with op.batch_alter_table('payments') as batch_op:
        batch_op.drop_column('transaction_id')
        
    with op.batch_alter_table('inventory_items') as batch_op:
        batch_op.drop_column('version')
        
    with op.batch_alter_table('halls') as batch_op:
        batch_op.drop_column('version')
        
    with op.batch_alter_table('employees') as batch_op:
        batch_op.drop_column('version')
        
    with op.batch_alter_table('audit_logs') as batch_op:
        batch_op.drop_constraint('fk_audit_logs_approval_requests', type_='foreignkey')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('approval_id')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('action_type')
        batch_op.drop_column('module_name')
        batch_op.drop_column('role')
        
    op.drop_index(op.f('ix_guest_bookings_temple_id'), table_name='guest_bookings')
    op.drop_table('guest_bookings')
    op.drop_table('cart_items')
    op.drop_table('temple_followers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_temple_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_change_requests_temple_id'), table_name='change_requests')
    op.drop_index('idx_change_requests_temple', table_name='change_requests')
    op.drop_index('idx_change_requests_status', table_name='change_requests')
    op.drop_index('idx_change_requests_entity', table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_temple_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_is_active'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_approval_requests_temple_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_is_active'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
